name: Cypress Testing
run-name: ${{github.actor}} run TestSuite in ${{github.ref_name}}
on:
    push:
      branches-ignore: [main]
#on: [workflow_dispatch] esto se usa para pushear y no ejecutar esto 
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: artefact mochawesome HTML and Json report
              if: always()
              uses: actions/upload-artifact@v3
              with:
                    name: report-Mochawesome_${{github.ref_name}}
                    path: cypress/test-result/mocha
                      
            
            - name: artefact Junit XML report
              if: always()
              uses: actions/upload-artifact@v3
              with:
                    name: report-Junit_${{github.ref_name}}
                    path: cypress/test-result/junit-report